name: 'Deploy to Azure'

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      azure_credentias:
        required: true
      resource_name:
        required: true

jobs:
  app_deploy_azure:
    name: ${{ inputs.job_name }}

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "RESOURCE_GROUP_NAME=rg-${{ secrets.resource_name }}${{ inputs.environment }}" >> $GITHUB_ENV
        echo "FUNCTION_APP_PATH=${{ github.workspace }}/published" >> $GITHUB_ENV
        echo "FUNCTION_APP_NAME=fncapp-${{ secrets.resource_name }}${{ inputs.environment }}" >> $GITHUB_ENV
    - name: Check environment variables
      shell: bash
      run: |
        echo $RESOURCE_GROUP_NAME
        echo $FUNCTION_APP_PATH
        echo $FUNCTION_APP_NAME
    - name: Download Function App artifact
      uses: actions/download-artifact@v2
      with:
        name: apiapp
        path: ${{ env.FUNCTION_APP_PATH }}
    
    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.azure_credentias }}
    
    - name: Get Function App publish profile
      id: publishprofile
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.azure_credentias }}
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        appName: ${{ env.FUNCTION_APP_NAME }}
    
    - name: Deploy Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: ${{ env.FUNCTION_APP_PATH }}
        publish-profile: ${{ steps.publishprofile.outputs.profile }}
    
    - name: Reset Function App publish profile
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.azure_credentias }}
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        appName: ${{ env.FUNCTION_APP_NAME }}
        reset: true